name: Benchmark

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build
        run: |
          go build -o mock_server ./cmd/mock_server
          go build -o main_server ./cmd/server

      - name: Start Mock Server
        run: |
          ./mock_server -size 10 &
          echo $! > mock_server.pid
          sleep 5

      - name: Start Reverse Proxy
        run: |
          ./main_server -target http://localhost:8080 -port 8000 &
          echo $! > main_server.pid
          sleep 5

      - name: Run benchmarks
        run: |
          go test ./internal/benchmark -bench=BenchmarkApiConcurrent -benchtime=1x -benchmem -cpuprofile=cpu.prof -memprofile=mem.prof | tee benchmark_results.txt

      - name: Stop servers
        run: |
          cat mock_server.pid | xargs kill || echo "Failed to kill mock server process"
          cat main_server.pid | xargs kill || echo "Failed to kill main server process"

      - name: Generate profile report
        run: |
          go install golang.org/x/perf/cmd/benchstat@latest
          $(go env GOPATH)/bin/benchstat benchmark_results.txt > benchstat_results.txt
          go tool pprof -output cpu_profile.html cpu.prof
          go tool pprof -output mem_profile.html mem.prof

      - name: Prepare gh-pages content
        run: |
          mkdir -p gh-pages
          mv benchmark_results.txt benchstat_results.txt cpu_profile.html mem_profile.html gh-pages/
          echo "<html><body><h1>Benchmark Reports</h1><ul>" > gh-pages/index.html
          for file in gh-pages/*; do
          echo "<li><a href='$(basename $file)'>$(basename $file)</a></li>" >> gh-pages/index.html
          done
          echo "</ul></body></html>" >> gh-pages/index.html          

      - name: Upload benchmark results
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages