name: Run Benchmarks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  benchmark:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install gobenchdata
        run: go install go.bobheadxi.dev/gobenchdata@latest

      - name: Run benchmarks
        run: go test -bench=. ./internal/proxy -benchmem -json > benchmark_results.json

      - name: Process benchmark data
        run: gobenchdata --json benchmark_results.json

      - name: Upload benchmark data
        uses: bobheadxi/gobenchdata@v1
        with:
          PRUNE_COUNT: 30
          BENCHMARKS_OUT: ./gobenchdata.json
          GO_TEST_FLAGS: -cpu 1,2
          PUBLISH: true
          PUBLISH_BRANCH: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
