name: Run Benchmarks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  benchmark:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install gobenchdata
        run: go install github.com/bobheadxi/gobenchdata@latest

      - name: Run benchmarks
        run: go test -bench=. ./internal/proxy -benchmem -json > benchmark_results.json

      - name: Process benchmark data
        run: gobenchdata --json benchmark_results.json

      - name: Upload benchmark data
        uses: bobheadxi/gobenchdata@v1
        with:
          PRUNE_COUNT: 30
          GO_BENCH_FILE: ./gobenchdata.json
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages